# Generated by Django 5.1.3 on 2024-11-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_member_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
